### PR TITLE
Fix dockerfile templates_c/ permission issue

### PR DESCRIPTION
**Pull request by samueltan3972**
Fix the error with permission issue in /var/www/html/templates_c/ folder when building docker image

### CODE REVIEW

**Comment by boombatower** [comment]
```
 > [13/13] RUN chmod 770 -R /var/www/html/templates_c/:
cannot access '/var/www/html/templates_c/': No such file or directory
```

**Comment by Rudloff** [comment]
That's strange, the folder does exist [here](https://gitlab.com/boombatower-container/alltube/-/tree/master/templates_c) and should have been copied by `COPY`. But maybe I'm missing something.
(I don't really maintain the Docker image anymore and leave it up to the community.)

**Comment by maxemoose** [comment]
Just a heads-up: I was building this Docker image on a Synology NAS and the process was still failing at step 13. Error was as follows: 

`mkdir: cannot create directory '/var/www/html/templates_c/': File exists`

Fixed by adding "-p" to the command mentioned in [f32412e](https://github.com/Rudloff/alltube/commit/f32412e861c88e987131d62ab812156b1702cecf) so that it becomes:

`RUN mkdir -p /var/www/html/templates_c/`

**Comment by Rudloff** [comment]
@maxemoose Would you like to submit a PR with this fix?

**Comment by maxemoose** [comment]
@Rudloff Can do. To follow.

Turned out I had another issue with that build though; The permissions set by step 14:
`RUN chmod 770 -R /var/www/html/templates_c/`

The addition of "-p" allowed the image to compile but running it Alltube could not show the web interface. Logs showed the following:
`Smarty: unable to write file /var/www/html/templates_c/wrt636.....`

Had to adjust step 14 to permissions 777 before Alltube could show the web interface again. Not an ideal solution but it will do until I can determine a better one.

**Pull request merged**
