### PR TITLE
fix video remuxing

### PR DESCRIPTION
**Pull request by jagub2**
As stated in title, space causes errors (output from ffmpeg):

```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x6bc6d80] Invalid stream specifier: v:0 .
    Last message repeated 1 times                          
Stream map '0:v:0 ' matches no streams.                    
To ignore this, add a trailing '?' to the map.
```

### CODE REVIEW

**Comment by Rudloff** [comment]
Hello,
Thanks for the fix and the translation!
(Although it is a good practice to use separate pull requests for unrelated changes.)

**Comment by Rudloff** [comment]
Whoops, I wanted to merge that on the develop branch...

**Comment by jagub2** [comment]
Whoops, I pushed first commit and created pull request. Didn't realize it would take newer commit 🤦🏻‍♂️
Sorry, I'll be more careful next time.

**Comment by kinglyl** [comment]
So....Can I update alltube now?

**Comment by Rudloff** [comment]
What do you mean?

**Comment by kinglyl** [comment]
I mean..Is that OK to 'composer update' now ?

**Comment by kinglyl** [comment]
It seems that I should use git to update...

**Pull request merged**
